var c = document.getElementById('firstCanvas');
var ctx = c.getContext('2d');
ctx.beginPath();
ctx.moveTo(10, 50);
ctx.lineTo(100, 150);
ctx.lineTo(300, 120);
ctx.lineTo(10, 50);
ctx.strokeStyle = 'green';
ctx.fillStyle = 'orange';
ctx.stroke();
ctx.fill();